- name: update apt
  command: apt-get update
- name: systemd about cadvisor
  command: "systemctl {{ item }}"
  with_items:
    - daemon-reload
    - enable cadvisor
    - restart cadvisor
- name: update grub2
  command: update-grub2
